name: Deploy master
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p '${{ secrets.DOCKER_PASSWORD }}'
      - run: docker build -t abdekwant/app -f Dockerfile.dev .
      
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*' 

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-react
          environment_name: Dockerreact-env-1
          existing_bucket_name: elasticbeanstalk-eu-central-1-913327590138
          region: eu-central-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
